name: Build and Deploy Kanban Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment: kanban-backend
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: kanban-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Create .env file from secrets
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        PORT: ${{ secrets.PORT }}
      run: |
        echo "The configured port is: $PORT"
        touch .env
        echo "POSTGRES_USER=$POSTGRES_USER" > .env
        echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
        echo "POSTGRES_DB=$POSTGRES_DB" >> .env
        echo "PORT=$PORT" >> .env

    - name: Start services with Docker Compose
      run: |
        docker compose -f docker-compose.yml up -d
        sleep 10

    - name: Debug PostgreSQL Logs
      if: failure()
      run: docker compose logs postgres
    
    - name: Check service health
      run: |
        docker compose ps
        curl -f http://localhost:3000/api || exit 1
    
    - name: Stop services
      if: always()
      run: docker-compose down -v
